# Generated by Django 3.2 on 2021-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_auto_20210420_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
